### ISSUE TITLE
Make database searchable

### ISSUE THREAD

**Issue by melchua** [melchua/dancewise#5]
## Acceptance Criteria
- [ ] All events by location
- [ ] All events by artist
- [x] All events by dance style
